### ISSUE TITLE
Failed to load extension Inkscape 0.92.4

### ISSUE THREAD

**Issue by erickvieira** [konsumer/inkscape-react#1]
- The extenssions log:
`Extension "React Output" failed to load because a dependency was not met.`
`Dependency:`
`  type: file`
`  location: path`
`  string: inkscape-react`
---
- The file is in ~/.config/inkscape/extensions directory:
![image](https://user-images.githubusercontent.com/17013722/71782181-16b90900-2fb6-11ea-9c52-dcca24f36d4a.png)
---
- The package was installed globaly:
![image](https://user-images.githubusercontent.com/17013722/71782692-c6dd4080-2fbb-11ea-91e8-d4e485b9f9f0.png)

**Comment by erickvieira** [comment]
After many attempts, I decided to report this issue. I am not sure about the real reason, because I use asdf to install Node versions, and **maybe** this has influenced somehow.

However, the attempt that really took effect in the current version of Inkscape (0.92.4) was as follows:

- add the header at the top of the `inkscape-react.inx` file:
![image](https://user-images.githubusercontent.com/17013722/71782808-1a03c300-2fbd-11ea-8b59-d4d19e10b8b2.png)
---
- copy the `~/.asdf/shims/inkscape-react` file to `~/.config/inkscape/extensions`
- ... and uncomment the  `<dependency>`tag on `inkscape-react.inx` file and write the `location` attribute, as above:
![image](https://user-images.githubusercontent.com/17013722/71782842-71099800-2fbd-11ea-81f1-81d6bbc3a013.png)
---
- at least, put the `reldir` attribute into the `<command>` tag insite the `script` scope, at the end of the file:
![image](https://user-images.githubusercontent.com/17013722/71782895-23d9f600-2fbe-11ea-8212-6d646ba3d315.png)
--- 
These steps has solved the problem to me. However, like I said, I'm not sure if my use case is common. But, since that, I'm able to export jsx components via Inkscape, like that:
![image](https://user-images.githubusercontent.com/17013722/71782963-f6da1300-2fbe-11ea-9fc6-04923d4ce8d2.png)

**Comment by konsumer** [comment]
Yeh, the inkscape plugin API, while very flexible with allowing any runtime that is installed on your system globally, can be a bit annoying when things are installed in some different way. Glad you got it working.
