### ISSUE TITLE
File cannot be saved

### ISSUE THREAD

**Issue by snspinn** [konsumer/inkscape-react#2]
G'day. 
Firstly; great project, thank for writing this!

# The issue
I'm running Windows10, have run the npm (global) install and copied the `inkscape-react.inx` into the relevant folder (I tried two different locations, more on that below). 
The tool shows up in the save menu but when I click to save the file, I am greeted with an error in the style `"File C:-....\<file-name>.jsx could not be saved"`.

### Screenshot

![image](https://user-images.githubusercontent.com/41950061/115708691-379e9c80-a368-11eb-8f95-54bacb080e0f.png)

# Attempts to fix it
I have tried placing `inkscape-react.inx` into two places, followed by a restart of inkscape (and a reboot of the machine when this failed to fix the issue)

1. `C:\Program Files\Inkscape\share\inkscape`
2. `C:\Users\<username>\AppData\Roaming\inkscape\extensions`

Running inkscape as admin was also tried out of desperation.

### Result
The same error as above.

# Conclusion to date
I've suspicious of the formating of the path shown in the error dialogue box, particularly the '-' symbol after the drive letter.

Any suggestions? 
Perhaps there's some way to get more detailed logging?

### Addendum
```
> node -v
v14.15.1
```

**Comment by snspinn** [comment]
## Update
Only after writing the above question did it dawn on me to try the cli option (It works).

### In Powershell
`inkscape-react {src-file-name}.svg > {target-file-name}.jsx`

This doesn't solve the above of course, but I'm just happy to be able to use this handy little tool. 🙏

**Comment by konsumer** [comment]
Hmm, I'm not sure how to reproduce this. It shouldn't be adding a dash to the path, and doesn't do this on any machine I have tested (windows, mac, linux.) I just tested now, on mac and it worked ok.

The inkscape documentation is sparse about how to actually set it up. I remember when I made this I had funny little issues with running it directly from non-global npm installs, as an example of weird stuff that isn't documented.

If I were you, I'd make sure inskcape is the latest version and reinstall the INX file in whatever is shown as your extension dir, in your inkscape preferences. here is mine, on my mac:

<img width="687" alt="Screen Shot 2021-04-22 at 11 18 32 AM" src="https://user-images.githubusercontent.com/83857/115766306-abd34300-a35c-11eb-95f3-4e9475cd089e.png">

also do a reinstall of the command-line tool, for good measure:

```
npm i -g inkscape-react
```

If it's still giving you trouble, I'd be willing to troubleshoot a bit over chat.

**Comment by snspinn** [comment]
Yes, it is tricky one to replicate.

I've tried
1. Updating node to the latest version,
2. reinstalling the npm package,
3. moving the `.inx` out of `App Data` and back into `Program FIles` (as per inkscape preferences box), and
4. downgrading from inkscape v1.0.2 to v1.0.1.

That weird newline and `-` disappeared after step 3. 🤷 

I also had issues saving to HTML 5 with version 1.0.2. It worked when moving down to 1.0.1 (this time installing with the `.msi` instead of the `.exe`). I'm staying away from the Microsoft Store for now...

I've also posted a question to the inkscape forum here: https://inkscape.org/forums/questions/save-as-html5-jsx-failing/

Thanks for the offer to help troubleshooting. I'll wait to hear back from the other forum first. I'll update any developments here.

**Comment by konsumer** [comment]
I'm going to close this, as it seems liek your issue is resolved, but feel free to report back anything else about it, here.

Seems like something generally weird about inkscape 1.0.2 install on your system. If you really want to use that version, maybe uninstalling it completely, then reinstalling inkscape 1.0.2. and doing same thing with plugins (go into the preferences to find the best plugin dir) might fix your issue, but it may just be a prob with that inkscape version. it's a good test to try another plugin, too. My plugin is a pretty thin inkscape-plugin wrapper around the node-module that does the work, so it can be hard to figure out what is causing the issue (is it node, the module, or inkscape?)
